wget ftp://ftp.ncbi.nlm.nih.gov/pub/wilbur/BioC-PMC/PMC000XXXXX_json_ascii.tar.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pub/wilbur/BioC-PMC/PMC030XXXXX_json_ascii.tar.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pub/wilbur/BioC-PMC/PMC035XXXXX_json_ascii.tar.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pub/wilbur/BioC-PMC/PMC040XXXXX_json_ascii.tar.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pub/wilbur/BioC-PMC/PMC045XXXXX_json_ascii.tar.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pub/wilbur/BioC-PMC/PMC050XXXXX_json_ascii.tar.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pub/wilbur/BioC-PMC/PMC055XXXXX_json_ascii.tar.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pub/wilbur/BioC-PMC/PMC060XXXXX_json_ascii.tar.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pub/wilbur/BioC-PMC/PMC065XXXXX_json_ascii.tar.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pub/wilbur/BioC-PMC/PMC070XXXXX_json_ascii.tar.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pub/wilbur/BioC-PMC/PMC075XXXXX_json_ascii.tar.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pub/wilbur/BioC-PMC/PMC080XXXXX_json_ascii.tar.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pub/wilbur/BioC-PMC/PMC085XXXXX_json_ascii.tar.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pub/wilbur/BioC-PMC/PMC090XXXXX_json_ascii.tar.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pub/wilbur/BioC-PMC/PMC095XXXXX_json_ascii.tar.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pub/wilbur/BioC-PMC/PMC100XXXXX_json_ascii.tar.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pub/wilbur/BioC-PMC/PMC105XXXXX_json_ascii.tar.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pub/wilbur/BioC-PMC/PMC110XXXXX_json_ascii.tar.gz
